name: On-Demand Test Execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: environment
        default: prod

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    concurrency: ${{ inputs.environment }}
    timeout-minutes: 45

    env:
      BASE_URL: ${{ vars.BASE_URL }}
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_API_URL: ${{ vars.BASE_API_URL }}
      CLIENT_ID: ${{ vars.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            .allure
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install chrome driver
        uses: browser-actions/setup-chrome@v1

      - name: Run Tests
        run: mvn test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-results